### ISSUE TITLE
House Numbers are always 4 Digit

### ISSUE THREAD

**Issue by Modelmat** [RandomAPI/Randomuser.me-Node#106]
When testing this API, house numbers are always 4 digits. This seems very illogical.
For instance, a call may return 
```json
"location": {
  "street": "8462 devon street",
  "city": "whanganui",
  "state": "northland",
  "postcode": 57129
},
```
 and the next call:
```json
"location": {
  "street": "9023 filistin cd",
  "city": "diyarbakır",
  "state": "isparta",
  "postcode": 37654
},
```
This does not seem very nice, it would be nice to see any number from 1 to 9999 included in results.

**Comment by keitharm** [comment]
Thanks for the suggestion, this'll be added in the next update.

**Comment by Modelmat** [comment]
I still haven't seen this yet?
