### ISSUE TITLE
Feature Request: Address break down

### ISSUE THREAD

**Issue by mickster04** [RandomAPI/Randomuser.me-Node#112]
Is it possible to have the location split into street number/name?

`"location": {
        "streetNumber": "5657",
        "streetName":"esk street",
        "city": "auckland",
        "state": "nelson",
        "postcode": 69709,
        "coordinates": {
          "latitude": "-4.6649",
          "longitude": "166.9746"
        },
        "timezone": {
          "offset": "-11:00",
          "description": "Midway Island, Samoa"
        }`

**Comment by keitharm** [comment]
This will be implemented in API v1.3
