### ISSUE TITLE
Data type for postcode, is it number or string?

### ISSUE THREAD

**Issue by montao** [RandomAPI/Randomuser.me-Node#113]
It looks like the data type sometimes is a number and sometimes it is a string. This is example output:

`"postcode":"F7Y 2D7"`

Therefore you might think that that the postcode is a string, but then there are also plain number types as well:

`"postcode":89756`

So it is difficult to write a JSON schema for this when the data type seems to change depending on what it is.

**Comment by RobinWPollard** [comment]
It would depend on the country. For example a US postcode is pure numeric, 32570, a British postcode is varchar, like ta19 5en a Dutch post code is like 1017EX
