### ISSUE TITLE
Set cell number for CH with 077 078 or 079 as prefix

### ISSUE THREAD

**Issue by laurentmuller** [RandomAPI/Randomuser.me-Node#114]
For cell number in Switzerland, only the following values are valid:
`077`, `078` or `079`

So the generation of cell number must like this:
```
var prefix= ['077', '078', '079'];
include(inc, 'cell', '(' + randomItem(prefix) + ')-' + random(3, 3) + '-' + random(3, 4));
```

**Comment by keitharm** [comment]
This issue will be fixed in version 1.3
