### ISSUE TITLE
CORS on localhost

### ISSUE THREAD

**Issue by adekbadek** [RandomAPI/Randomuser.me-Node#120]
The API is not accessible on localhost due to CORS restrictions. Would you welcome a PR enabling it, or is there a specific reason for blocking localhost requests?

**Comment by keitharm** [comment]
The CORS access-control-allow-origin is currently set to the wildcard '*' on the server, so all requests should be able to get through. One problem that could cause CORS to block your request is if you are sending it with `withCredentials` enabled.

If you've verified that you don't have `withCredentials` enabled, could you please provide a snippet of how you are calling the api or maybe a screenshot of what specific error you're getting? Thanks!

**Comment by adekbadek** [comment]
I can't reproduce this issue anymore. 
It was probably some caused by something else and I jumped the gun, sorry for that!
