### ISSUE TITLE
Phone number format not always valid

### ISSUE THREAD

**Issue by exaynorsa** [RandomAPI/Randomuser.me-Node#123]
Generating a phone number for Germany leads to an invalid number 50% of the time, according to the Google phone number library ( https://github.com/googlei18n/libphonenumber ).

**Comment by fiznool** [comment]
British cell (mobile) numbers are also formatted (e.g.) 0739-170-316, which isn't quite correct:

- GB mobile numbers are 11 digits starting with 07
- It's common to see GB mobile numbers in the form `07xxx xxxxxx` rather than hyphen delimited
