### ISSUE TITLE
Correlation between danish CPR number and DOB

### ISSUE THREAD

**Issue by YnkDK** [RandomAPI/Randomuser.me-Node#125]
---
name: Bug Report
about: Using the nationality DK has incorrect correlation between DOB and CPR.
labels: kind/bug

---

**What happened**:
I used the random user API with the following parameters [?nat=dk&seed=danishNationality](https://randomuser.me/api/?nat=dk&seed=danishNationality)

**What you expected to happen**:
It was expected that the CPR and DOB was correlated, i.e. If DOB was 1957-10-07, then the CPR number should be 071057-????. To generalize this: DOB YYyy-MM-DD should yield a CPR number on the format DDMMyy-????, where ???? is random integers.

**How to reproduce it (as minimally and precisely as possible)**:
https://randomuser.me/api/?nat=dk&seed=danishNationality

**Comment by keitharm** [comment]
Thanks for the report, this will be fixed in API v1.3.
