### ISSUE TITLE
Location of danish nationalities

### ISSUE THREAD

**Issue by YnkDK** [RandomAPI/Randomuser.me-Node#126]
---
name: Bug Report
about: Using the nationality DK has non-meaningful location
labels: kind/bug

---

**What happened**:
I used the random user API with the following parameters [?nat=dk&seed=danishNationality](https://randomuser.me/api/?nat=dk&seed=danishNationality)

**What you expected to happen**:
That the location data matches Danish addresses.

**How to reproduce it (as minimally and precisely as possible)**:
https://randomuser.me/api/?nat=dk&seed=danishNationality

**Anything else we need to know?**:
You can use the official Danish list of addresses that can be found at: https://dawa.aws.dk/adgangsadresser (It is a rather large file). 
Documentation can be found here: https://dawa.aws.dk/dok/api/adgangsadresse

Mapping:
city -> postnummer.navn
coordinates.longitude-> adgangspunkt.koordinater[0]
coordinates.latitude -> adgangspunkt.koordinater[1]
postcode -> postnummer.nr
state -> storkreds.navn
timezone -> always CEST or CET with Copenhagen as reference

**Comment by keitharm** [comment]
Wow you weren't kidding it is a huge file (8.7G)! Thanks for the resource, will try and incorporate this with the upcoming v1.4 update.
