### ISSUE TITLE
Proper casing of names

### ISSUE THREAD

**Issue by blewisio** [RandomAPI/Randomuser.me-Node#127]
First and last names and some other fields like address are all lowercase, which doesn't match grammar rules (at least in English, I'm not sure about other languages). Is there a reason they are all lowercase, or could this be updated?

**Comment by keitharm** [comment]
Names and dates such as DoB/Registered are kept in their "purest" forms to keep them unopinionated and let the user decide how to format the data.

**Comment by blewisio** [comment]
@keitharm thanks for the reply!

I don't know what pure or unopinionated means when it comes to a person's name. In what scenario would somebody want an all lowercase name or address...?

If a user still wanted all lowercase after the change, they could call `.toLowerCase()` (ex. JS) without much trouble to get the current format.

**Comment by keitharm** [comment]
You make a good point: While dates should follow some standard format that is easy to change to respective localizations, names are almost always first letter capitalized as far as I know.

I wanted to try and not force a particular format for names, but all lowercase is an uncommon format after all.

Names and and addresses will be properly formatted in the v1.3 release of the api.
