### ISSUE TITLE
space in email

### ISSUE THREAD

**Issue by spidfire** [RandomAPI/Randomuser.me-Node#133]
I generated a ?format=csv&results=5000 CSV but I found a email with spaces after which my system crashed

Fernao de Magalhaes.daLuz@example.com

I guess this can be fixed by replacing spaces with underscores on the following line

https://github.com/RandomAPI/Randomuser.me-Node/blob/33d943d2cd18600354fb423cdd3790b331081850/api/1.3/api.js#L173

Maybe it is also nice to make the mail lowercase?

**Comment by keitharm** [comment]
Looks like only the last name is currently having spaces replaced. I'll try and push a fix for this in a bit.
