### ISSUE TITLE
Issue while using Seeds

### ISSUE THREAD

**Issue by virenkheni** [RandomAPI/Randomuser.me-Node#143]
I want only **female** from Australia and i am using **seeds** to get same data because i am using pagination. In this, if you call this URL "https://randomuser.me/api/?page=1&results=10&gender=female&nat=au&seed=aubar" you will get **male** user also.

**Comment by keitharm** [comment]
Seed is kind of finicky in that it requires the exact same parameters that were provided to it when it generated the dataset.
For example, you can use the same seed foobar but specify one with nat US and another with nat AU. Both of the datasets will be different from each other, but the same datasets will be returned if you use the same seed and same parameters (nat).
