### ISSUE TITLE
Dutch postcodes are wrong 

### ISSUE THREAD

**Issue by RobinWPollard** [RandomAPI/Randomuser.me-Node#145]
The format of a Dutch post code is four digits and two characters, like 1015DF. The code currently generates pure numeric.

**Comment by RobinWPollard** [comment]
I also notice phone numbers for NL are wrong too

  "phone":"(420)-031-4976"
  "cell":"(376)-980-1922",

The phone is more like (020) 472 3826 and the cell numbers all have the 'area code' 06 then 8 more digits. I am looking at making a patch, but I can't see quite how I am meant to connect to MongoDB yet so have not got it running.

**Comment by RobinWPollard** [comment]
OK, I have fixed this in inject.js for NL. Now I must need to work out how to get this fix up to github...

**Comment by keitharm** [comment]
Changes merged in https://github.com/RandomAPI/Randomuser.me-Node/pull/146
