### ISSUE TITLE
Minor phone number formatting issue

### ISSUE THREAD

**Issue by mlevin2** [RandomAPI/Randomuser.me-Node#149]
North American phone numbers should be one of these:

- (NPA) NXX-XXXX
- NPA-NXX-XXXX

The data returned looks like this:

```json
{ "phone": "(912)-464-7839" }
```

So if you use parentheses, don't put a dash after them. Either format is fine, but don't combine them :-)

I submitted pull request #150 for this

Update: also fixed it so that neither NPA nor NXX can start with a 0 or 1

**Comment by keitharm** [comment]
Changes merged in https://github.com/RandomAPI/Randomuser.me-Node/pull/150
