### ISSUE TITLE
The site is down Error 502

### ISSUE THREAD

**Issue by jenna14wls** [RandomAPI/Randomuser.me-Node#151]
The site is down Error 502

**Comment by jenna14wls** [comment]
Any news when will be up again????

**Comment by JoshuaPerk** [comment]
Having to migrate to a local version due to this extended outage.

**Comment by jenna14wls** [comment]
Somebody knows anything when will be up again? What will be a local version? Thank you

**Comment by JoshuaPerk** [comment]
@keitharm Will this project still be maintained? @jenna14wls You can either replace the "randomness" with hardcoded assets like names and images or you can build the project on your own server as described here: https://github.com/RandomAPI/Randomuser.me-Node#how-to-use

**Comment by jenna14wls** [comment]
Thank you so much @JoshuaPerk

**Comment by rubencougil** [comment]
🙋‍♂ I'm affected by the outage too, just in case  I've just created a Dockerized version:

https://hub.docker.com/r/rcougil/randomuser

Feel free to use it if you find it useful.

**Comment by JoshuaPerk** [comment]
Looks like the site is finally back up. Hopefully the folks here can give us an update so we can determine if this was a fluke or if we should establish alternatives to this API.

**Comment by tomasiewicz-dominik** [comment]
Again the service is down

**Comment by keitharm** [comment]
Sorry for the the site and repo's neglect for the last few years. I'll be trying to push out a minor v1.4 update later this week with some much needed PRs being merged and issues addressed.

Also have plans for a major update including a redesign, dockerization, and gql api, but no ETA currently.
