### ISSUE TITLE
Password Generation

### ISSUE THREAD

**Issue by yasinersever** [RandomAPI/Randomuser.me-Node#152]
Although the character set is given, it sometimes does not create a character from the specified character set.

Example generated password: W<]OWS{+'G
Requested features: upper, lower, special, number
There is no character from the small and number character set.

**Comment by keitharm** [comment]
Make sure that there are no spaces between the requested features. This'll be addressed in the upcoming v1.4 update to strip whitespace from the requested character sets.

Ex: https://api.randomuser.me/?password=upper,lower,special,number&inc=login
