### ISSUE TITLE
Donation Not Still Work

### ISSUE THREAD

**Issue by James12Borek** [RandomAPI/Randomuser.me-Node#153]
i test my credit card on randomuser.me and its' say's "Bad Request (we can't procced your pâyment)" i Think It's Connection or error in my pc but i test in new connection and pc it's give the same error "we can't procced your pâyment"
i contact my bank and they said there is no error in credit card 
i saw it's powred by stipe i contact stripe to see if may credit card are available to use in stripe and they say "yes you can"

**Comment by keitharm** [comment]
Sorry about that, donations should be working now at least. It may have been a webserver issue on our end at the time.
