### ISSUE TITLE
Issue with seeds + inc parameter

### ISSUE THREAD

**Issue by spunka** [RandomAPI/Randomuser.me-Node#155]
Hi. If you fetch this data:
https://randomuser.me/api/?results=10&seed=foobar
The first name is Miss Britney Sims and the last Mrs Addison Ross

But if you add the "inc" parameter, the data is different
https://randomuser.me/api/?results=10&inc=gender,name,email,nat&seed=foobar
The first name is Miss Britney Sims and the last Mrs Evelyn Lane

Is this an issue or is this normal? Because i want to export less data than the one i use on my page, and is not the same
Thanks!

**Comment by keitharm** [comment]
Seed is kind of finicky in that it requires the exact same parameters that were provided to it when it generated the dataset.
For example, you can use the same seed `foobar` but specify one with nat US and another with nat AU. Both of the datasets will be different from each other, but the same datasets will be returned if you use the same seed and same parameters (nat).

This behavior is expected but admittedly wasn't the original intention.
