### ISSUE TITLE
DateOfBirth may generate incorrect age.

### ISSUE THREAD

**Issue by chriswill** [RandomAPI/Randomuser.me-Node#156]
Here's a DOB entry for a user that was retrieved today, July 2, 2020.

`            "dob": {
                "date": "1990-10-20T16:00:26.128Z",
                "age": 30
            },`

This user would turn 30 on Oct 20, 2020.  Today is not yet that date.  The user should appear as 29 years old.

**Comment by keitharm** [comment]
This will be fixed in the upcoming v1.4 update. Hoping to release it later this week.
