### ISSUE TITLE
Typo in Json schema desription 

### ISSUE THREAD

**Issue by igorsan98v2** [RandomAPI/Randomuser.me-Node#157]
According to JSON schema at https://randomuser.me/ field "street" looks like this:
![image](https://user-images.githubusercontent.com/34813105/86851100-08f65480-c0bb-11ea-94fe-145fe4ce1b27.png)
but in fact, according to last API, field "street" must be looks like this: 
<code>
     "street": {
          "number":  "some number " ,
          "name":  "some name"
     }
</code>
It is may produce some confuses for using API with a strong typed languages

**Comment by korki43** [comment]
yes, do you want to fix it?

**Comment by keitharm** [comment]
Thanks for pointing this out, this'll be addressed in the upcoming v1.4 update.
