### ISSUE TITLE
we getting 502 Bad Gateway for https://randomuser.me/ can we get a fix for this please?

### ISSUE THREAD

**Issue by chennasuman** [RandomAPI/Randomuser.me-Node#159]
Step 1) hitting https://randomuser.me/ we getting 502 Bad Gateway.
<img width="1128" alt="502 Bad Gateway" src="https://user-images.githubusercontent.com/7448979/87311953-d8c61000-c517-11ea-85d7-afbc58fc2ce5.png">

**Comment by amrmostafa800** [comment]
site down for all :(

**Comment by arronhunt** [comment]
This issue has been resolved, thanks @chennasuman for reporting 👍
