### ISSUE TITLE
'#' and '&' characters in the SEED parameter cause random data generation (V1.3)

### ISSUE THREAD

**Issue by dozzah0208** [RandomAPI/Randomuser.me-Node#161]
I was testing different seed values and combinations of characters, double checking that same data is generated each time. 

I found that "#" and "&" characters tend to act as string terminators, and if used on their own, generate data as if no seed is present. 

Placing one of these characters in the middle of the seed string, produces consistent data values, but the seed in the "info" object only takes into consideration the characters "#"/"&".

To recreate, include seed parameter and give it a value containing either of the characters such as:

- https://randomuser.me/api/?seed=<sp_char>
or
- https://randomuser.me/api/?seed=<"string"><sp_char><"string">

Screenshots are attached.

<img width="797" alt="In_the_middle" src="https://user-images.githubusercontent.com/47976808/87421514-f609e580-c5ce-11ea-901f-690e6a393a78.png">
<img width="800" alt="Start" src="https://user-images.githubusercontent.com/47976808/87421523-f86c3f80-c5ce-11ea-81ab-3da04010b775.png">
<img width="798" alt="Start2" src="https://user-images.githubusercontent.com/47976808/87421525-f99d6c80-c5ce-11ea-9abe-aaf995d39b37.png">

**Comment by vmuresanu** [comment]
If we search for "safe url characters" you may find out that Alphanumerics ```[0-9a-zA-Z]```, and some special characters like ```$-_.+!*'()```  are acceptable in Url and are considered "safe" to use. Also ASCII control characters and Non ASCII can also be used but have to be encoded. Aside from those, we have some Reserved Characters : ```; / ? : @ = &``` and finally Unsafe cahracters: ```Includes the blank/empty space and " < > # % { } | \ ^ ~ [ ] ```. 

What you've used here are Reserved Character - & which is used to append a queryParam and and Unsafe "#" which in modern single page front-end applications like Angular, React etc. indicates to browser that it should not make API calls after # and everything after "#" symbol is for internal (Angular, React etc.) router to load javascript pages (This is called a Hash location strategy).

And to be honest with you, I really can't find a usecase why would you possibly use # or & (aside from queryparams) in a request.

**Comment by dozzah0208** [comment]
@vmuresanu Thanks for your reply! I have considered that this may be the case, and have tested the other query parameter chars (all of which worked). For this reason I thought that there may have been a missed case with the "#" and "&".
