### ISSUE TITLE
Two surnames for Spain

### ISSUE THREAD

**Issue by atnbueno** [RandomAPI/Randomuser.me-Node#167]
In Spain we use two surnames, one from each parent. As a workaround I request 2x names from the API and use the extra surnames as second ones, but it would be much more convenient to have the option to directly request two of them.

**Comment by atnbueno** [comment]
I forgot: not that it's impossible to happen IRL, but in the case of requesting two surnames I would avoid repeating the same surname. Repeated surnames really grab the attention.

**Comment by keitharm** [comment]
Thanks for the suggestion, this'll be added in the upcoming v1.4 update coming out later this week.

**Comment by atnbueno** [comment]
I just tested this in v1.4 and I only got a single surname 😢
