### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by Kumar85** [RandomAPI/Randomuser.me-Node#170]
![Screenshot_2020-07-25-13-40-42](https://user-images.githubusercontent.com/58109796/88451964-a81d9900-ce7c-11ea-8b37-1913602cc219.png)
Access to XMLHttpRequest at 'https://randomuser.me/api/?results=1' from origin 'https://randomuser.me/api/?results=1' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by keitharm** [comment]
We were having some web server issues at the time. Some server upgrades will be coming in the near future after the v1.4 update comes out to help prevent the api from overloading.
