### ISSUE TITLE
Api Server not sending CORS (Access-Control-Allow-Origin) Header

### ISSUE THREAD

**Issue by bertbeck** [RandomAPI/Randomuser.me-Node#186]
I can't load randomuser.me data anymore using json as I get the error "No CORS headers found". When I check randomuser.me with a web sniffer, I see that the correct header Access-Control-Allow-Origin is not present

I looked at the github node server source code and in face it doe enable CORS. Maybe cloudflare is causing problems or the server needs a reboot?

This problem started a few days ago - before that - all was working fine.

See:

![Screen Shot 2020-12-26 at 1 11 36 PM](https://user-images.githubusercontent.com/6159170/103157026-0b3d8f80-477d-11eb-8a6a-c3563d15f519.png)

**Comment by omnibrain** [comment]
I'm having the same problem, but only about half of the requests fail, for the other half everything works just fine:

<img width="1166" alt="Screenshot 2021-01-10 at 10 27 55" src="https://user-images.githubusercontent.com/2551508/104119267-892d9900-532e-11eb-80c4-89daf60ea0c1.png">

**Comment by keitharm** [comment]
Issue should be resolved - closing for now. Please reopen if you experience CORS problems again, thanks.

**Comment by br441** [comment]
@bertbeck Can you reopen this? I'm getting the same error about 50% of the time now.
