### ISSUE TITLE
Passing seed and gender query parameters gives wrong results

### ISSUE THREAD

**Issue by La-BeTe** [RandomAPI/Randomuser.me-Node#188]
When I query the API and pass a seed as well as a gender, the returned results also contain users of the opposite gender.
This is also extremely noticeable when I pass page as one of the queries.

An example of this type of anomaly is [HERE](https://randomuser.me/api/?exc=login&seed=foobar&results=10&gender=male&page=2) .

**Comment by keitharm** [comment]
Seed is kind of finicky in that it requires the exact same parameters that were provided to it when it generated the dataset.
For example, you can use the same seed foobar but specify one with nat US and another with nat AU. Both of the datasets will be different from each other, but the same datasets will be returned if you use the same seed and same parameters (nat).

It also looks like there maybe some issues with the seed parameter overriding gender. Will need to investigate this a big more, should be able to have a fix out in the v1.4 update coming out later this week.
