### ISSUE TITLE
JSON Formatting Inconsistency

### ISSUE THREAD

**Issue by Ryan-Gross1993** [RandomAPI/Randomuser.me-Node#194]
When calling the endpoint, the location is split into two field, while it's showing as one in the documentation.

It's a minor fix that might save some developer's a headache or two. 😉 

Unrelated, thank you for this open-source contribution! :) 

<img width="415" alt="endpoint" src="https://user-images.githubusercontent.com/20117605/133666612-fefe0a0f-767d-4fdd-ab40-4779f4bdd1ec.png">
<img width="342" alt="documentation" src="https://user-images.githubusercontent.com/20117605/133666614-1728a7ce-f63c-40d9-a5cd-a7b328cb3a36.png">

**Comment by dimitri-bret** [comment]
yes, i had this too :D

**Comment by Ryan-Gross1993** [comment]
Sure! :)

**Comment by keitharm** [comment]
Related: https://github.com/RandomAPI/Randomuser.me-Node/issues/157

The live version will be updated to reflect the repo when v1.4 comes out hopefully later this week.
