### ISSUE TITLE
SSN fails validation per pattern rules

### ISSUE THREAD

**Issue by zhangbanger** [RandomAPI/Randomuser.me-Node#196]
Per these rules, we can't have US SSNs with with certain patterns:

https://www.ssa.gov/kc/SSAFactSheet--IssuingSSNs.pdf

A few notes:

- Can't start with 9
- Can't start with 666
- Can't have all 0's in any dashed section (the first 3, middle 2, or last 4)

**Comment by keitharm** [comment]
Fixed in https://github.com/RandomAPI/Randomuser.me-Node/pull/174
