### ISSUE TITLE
French INSEE numbers are wrong

### ISSUE THREAD

**Issue by seishonagon** [RandomAPI/Randomuser.me-Node#197]
The French ID numbers (INSEE) are wrong: 
here's an example : (Elia Gaillard),2NNaN51189076 93
1) the 2 is correct (female; 1 for male)
2) NNaN should be 7703 since she was born on 23 mars 1977
3) The final 93 should be 13. This 2 digit key is computed as follows for a number NNNNNNNNNNNNN: 
KK = 97 - ( ( NNNNNNNNNNNNN ) mod 97 )

So the true number should be 2770351189076 13

**Comment by keitharm** [comment]
This will be fixed in the upcoming v1.4 update.
