### ISSUE TITLE
Problem in extension photoshop 

### ISSUE THREAD

**Issue by SoufianeAbid** [RandomAPI/Randomuser.me-Node#64]
hello 
i have problem in extension photoshop 

http://i.imgur.com/SVd27AY.png

**Comment by keitharm** [comment]
Hm, not sure what could be causing that error. The image path is valid and also you can see that it did fetch the image properly in the preview window.

Is this the 1st time you have experienced this issue?

**Comment by SoufianeAbid** [comment]
No he was working well
