### ISSUE TITLE
Option to configure password policy

### ISSUE THREAD

**Issue by roo7break** [RandomAPI/Randomuser.me-Node#74]
It would be great if its possible to configure a password policy to randomly generate a password instead of reading from file.

**Comment by keitharm** [comment]
Sounds like a good idea! Any idea what the charset for the randomly generate passwords should be?

Maybe by default it'll use the charset `A-z0-9`.
And then if the user wants, they can specify their own charset.

**Comment by roo7break** [comment]
Have Boolean variables like:

Commonpassword - default yes
Special_char - default no
Upper_case - default no
Lower_case - default no
Number - default no
Length - default no

These can be turned on and off on demand. When selected it can choose random number of each chat type. 

Regards

Nikhil

**Comment by keitharm** [comment]
How about it uses a system similar to `inc` and `exc` where you can provide multiple options in a comma delimited list.

Something like `?password=special,upper,lower,number,1-25` = special, uppercase, lowercase, and number chars with a length between 1 and 25.

You could then mix and match those options depending on the type of password string you want generated.
`password=upper,number,16` = Uppercase and number chars exactly 16 chars long
`password=special,8` = special characters exactly 8 chars long
`password=lower,1-20` = Lowercase characters 1 to 20 chars long`

By default, not specifying any password options will choose randomly from the password list like it currently does.

**Comment by roo7break** [comment]
Sounds like a plan. If possible , adding suffix and prefix for password would also be helpful. 

Nik
