### ISSUE TITLE
Bigger images?

### ISSUE THREAD

**Issue by kylescousin** [RandomAPI/Randomuser.me-Node#82]
Apparently even the big image is only a 128x128 thumbnail - is there a way to retrieve the full size image of a user?

**Comment by arronhunt** [comment]
@kylescousin Unfortunately since we're pulling the images from uifaces.com, 128 is the largest size we're able to grab :(

**Comment by kylescousin** [comment]
Ok. There's usually a bigger picture available on Twitter. Perhaps use the Twitter API to retrieve that url and include it in the json?
