### ISSUE TITLE
Extra space at the end of last name steeves

### ISSUE THREAD

**Issue by ajcolub11** [RandomAPI/Randomuser.me-Node#92]
https://github.com/RandomAPI/Randomuser.me-Node/blob/92c811d841648c5ce85d418571b1fd52996ea18a/api/.nextRelease/data/US/lists/last.txt#L264

Hello,

had some repeated test failures due to an extra space at the end of the last name "steeves". I attempted to clone this repo, but was having a bit of difficulty getting everything running, figured this changed was easy enough to just communicate to you all. Is there any chance we can get that space removed?

Thank you for your consideration.

**Comment by keitharm** [comment]
It's been hotfixed, thanks for letting us know
