### ISSUE TITLE
Multiple Parameters not working

### ISSUE THREAD

**Issue by itchap** [RandomAPI/Randomuser.me-Node#95]
Hi

Im trying to pull 25 female users like this but im getting both males and females.

curl https://randomuser.me/api/?results=25&gender=female

Also tried to get 25 results and only include gender value but it's also not working.

curl https://randomuser.me/api/?results=25&inc=gender

Any help?

Thanks

**Comment by keitharm** [comment]
I am not too sure what the problem is that your experiencing?
It looks like both of those API calls with those options are working.
