### ISSUE TITLE
Skip the Arabic names

### ISSUE THREAD

**Issue by sandropoluan** [RandomAPI/Randomuser.me-Node#96]
I don't want to receive the Arabic names.
I have set `https://randomuser.me/api/?results=15&?nat=us` , but still showing up.
Did something I miss?
Thank you.

**Comment by arronhunt** [comment]
Looks like you’re using `?` instead of `&` on your second parameter

`https://randomuser.me/api/?results=15&nat=us`

**Comment by sandropoluan** [comment]
oh my god... I didn't notice that. Thank you.
