### ISSUE TITLE
Support querying by id

### ISSUE THREAD

**Issue by aze3ma** [RandomAPI/Randomuser.me-Node#97]
API not support querying by id and also not respect the RESTful API conventions so it can support as separate action such as (https://randomuser.me/api/users/:id) or at least as parameter such as (https://randomuser.me/api/?user_id="id").

**Comment by keitharm** [comment]
Instead of user ids, the API can accept a seed that will return the same user/users that are generated with a request (https://randomuser.me/api/?seed=foobar).
